### ISSUE TITLE
Phase 1 - User Research

### ISSUE THREAD

**Issue by Hachiko97** [deco3500-2017/3-Amigos#2]
# User Personas
Creating our user group to fully understand what is needed to fully address the issue we are trying to solve.

- [x] Create user personas (3-5 personas)

# User Survey
Create a online questionnaire to extract actionable feedback from intended users.
- [x] Create Google Forms survey
- [x] Perform survey
- [x] Collect and analyse data

**Comment by alsatiax** [comment]
Here are a few good resources I found that give insight into our potential user group:
[http://www.educationworld.com/a_tech/5-tech-tools-to-boost-teacher-to-parent-communication.shtml](url)
[http://www.adi.org/journal/ss05/Graham-Clay.pdf](url)
[https://edtechmagazine.com/k12/article/2016/08/4-apps-foster-parent-teacher-communication](url)
[http://www.gallup.com/businessjournal/186026/crucial-element-successful-schools-parent-engagement.aspx](url)

**Comment by alsatiax** [comment]
Just got in contact with my cousin who is a primary school teacher. She really liked the idea of Eduboard and suggested that she at least would prefer a system she can access from her phone. She mentioned that in classtime breaks she could then share articles more easily from her phone without this taking up too much of her personal time. In terms of personal chat between teachers and parents, my cousin said she'd prefer to not have chat functionality within the app but rather commenting functionality on posts and then a link to the teacher email so that the teacher can then respond to emails in work time. She also said that the priority should be on the teacher posting up articles rather than parents too otherwise it might be too messy/unorganised. Or even have functionality that allows for a teacher to admin and confirm posts.
